name-template: 'v$RESOLVED_VERSION 🦄'
tag-template: 'v$RESOLVED_VERSION'

category-template: '## $TITLE'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor' 
      - 'feature' # for now as it is pre 1.0
  patch:
    labels:
      - 'chore'
      - 'patch'
  default: patch

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'

exclude-labels:
  - reverted
  - no-changelog
  - skip-changelog
  - invalid

autolabeler:
  - label: 'bug'
    title:
      - '/^fix/i'
  - label: 'feature'
    title:
      - '/^feat/i'
  - label: 'chore'
    title:
      - '/^chore/i'

template: |
  We are very prod to release version $RESOLVED_VERSION 🌈

  <!-- Optional: add a release summary here -->

  ## What's new 👶

  $CHANGES

  ## Contributors

  Thanks to these the folks that made this release possible 🙇‍♂️

  $CONTRIBUTORS	
