name-template: 'v$RESOLVED_VERSION ðŸ¦„'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor' 
      - 'feature' # for now as it is pre 1.0
  patch:
    labels:
      - 'chore'
      - 'patch'
  default: patch

categories:
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ðŸ§° Maintenance'
    label: 'chore'
category-template: '## $TITLE'
autolabeler:
  - label: 'bug'
    title:
      - '/^fix/i'
  - label: 'feature'
    title:
      - '/^feat/i'
  - label: 'chore'
    title:
      - '/^chore/i'
template: |
  We are very prod to release version $RESOLVED_VERSION. See what has changed below!

  ## What's new ðŸ‘¶

  $CHANGES

  ## Contributors

  Thanks to these the folks that made this release possible ðŸ™Œ

  $CONTRIBUTORS	
