// NOTE:
// if you want to export a single file just use the fileName within src, eg: 'MyComponent' => MyComponent.js and MyComponent.cjs
// if you want to export a whole folder point to the index withing, eg: 'Box/index' => Box/index.js and Box/index.cjs

export const packageExports = [
  'index',
  'animation/index',
  'Avatar/index',
  'Box/index',
  'breakpoints/index',
  'Button/index',
  'ButtonBar/index',
  'ButtonBase/index',
  'Card/index',
  'Checkbox/index',
  'ClickOutside/index',
  'IconButton/index',
  'Image/index',
  'Input/index',
  'FlexGrid/index',
  'Hide/index',
  'Link/index',
  'Menu/index',
  'Modal/index',
  'NativeSelect/index',
  'Popover/index',
  'PopoverArrow/index',
  'Portal/index',
  'Radio/index',
  'Show/index',
  'Slider/index',
  'SidebarNav/index',
  'Switch/index',
  'Tabs/index',
  'TextArea/index',
  'theme/index',
  'ToastCard/index',
  'ToastProvider/index',
  'Toolbar/index',
  'Tooltip/index',
  'Typography/index',
  'styleHelpers/index',
];
