name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: install
        run: 'yarn'

      - name: Test
        run: yarn test
      
      - name: Build
        run: yarn build

      - name: Authenticate with registry
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: deploy
        run: yarn run deploy
