name: Release Tagger
on: 
  workflow_dispatch:
    inputs:
      version_should_match:
        description: 'Version should match (optional)'
        required: false

jobs:
  releaseVersion:
    name: "Release new version"
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Publish new version ${{ github.event.inputs.version }}"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Set git commit author
      run: |
        git config --global user.name "Pablo Bot"
        git config --global user.email bot@bojagi.io
    - name: install
      run: 'yarn'
    - run: |
        export VERSION_SHOULD_MATCH=${{ github.event.inputs.version_should_match }}
        export RELEASE_VERSION=$(node ./scripts/getDraftReleaseVersion)
        yarn run publish
        node ./scripts/publishDraftRelease
      name: 'Publish'
      env:
        GITHUB_TOKEN: ${{ github.token }}
