name: Release Tagger
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true
        default: '0.x.x'

jobs:
  releaseVersion:
    name: "Release new version"
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Publish new version ${{ github.event.inputs.version }}"
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: install
      run: 'yarn'
    - run: |
        RELEASE_VERSION=$(node ./scripts/getDraftReleaseVersion)
        yarn run publish $RELEASE_VERSION
      name: 'Publish'
      env:
        GITHUB_TOKEN: ${{ github.token }}
