name: Size Limit

on:
  pull_request:
    branches:
      - main

jobs:
  sizeLimit:
    name: Size Limit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - uses: andresz1/size-limit-action@v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
